//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EF_HW_2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Books
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public int PagesCount { get; set; }
        public Nullable<int> Author_Id { get; set; }
        public Nullable<int> Category_Id { get; set; }
        public Nullable<int> Press_Id { get; set; }
    
        public virtual Authors Authors { get; set; }
        public virtual Categories Categories { get; set; }
        public virtual Presses Presses { get; set; }

        public override string ToString() => $"Book name: {Name}\t\tPages count: {PagesCount}\t" +
                                             $"{Authors}\tPress: {Presses}\tCategory: {Categories}";
    }
}
